FROM python:3.12-slim

WORKDIR /app

COPY requirements-model.txt .

RUN pip install --no-cache-dir -r requirements-model.txt

COPY src/api.py src/api.py
COPY models/fraud_model.pkl models/fraud_model.pkl

EXPOSE 8080

CMD ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8080"]